# Generated by Django 4.2.13 on 2026-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
