# Generated by Django 4.2.13 on 2026-06-27 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_campaign_variables'),
        ('sequences', '0001_initial'),
        ('analytics', '0002_snapshot_contact_on_sendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='sequence_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='sequences.sequencestep'),
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='campaigns.campaign'),
        ),
    ]
