# Generated by Django 4.2.13 on 2026-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_sendlog_sequence_step_alter_sendlog_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sendlog',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('unsubscribed', 'Unsubscribed'), ('complained', 'Complained'), ('replied', 'Replied')], default='pending', max_length=20),
        ),
    ]
