# Generated by Django 4.2.13 on 2026-06-30 08:43

from django.db import migrations, models
import django.db.models.deletion


def clear_old_campaign_links(apps, schema_editor):
    """
    SendLog.campaign is being repointed from the old (about to be deleted)
    campaigns.Campaign to the new unified sequences.Campaign. Per the
    decision to drop old Campaign data entirely, any SendLog still pointing
    at one of those old blast campaigns has nothing valid to point at
    anymore — null it out rather than leave (or fail on) a dangling FK.
    """
    SendLog = apps.get_model('analytics', 'SendLog')
    SendLog.objects.filter(campaign_id__isnull=False).update(campaign_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0006_rename_sequences_s_status_5df17f_idx_sequences_c_status_459095_idx'),
        ('analytics', '0005_trackingdomain'),
    ]

    operations = [
        migrations.RunPython(clear_old_campaign_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sendlog',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='sequences.campaign'),
        ),
    ]
