# Generated by Django 4.2.13 on 2026-06-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0006_rename_sequences_s_status_5df17f_idx_sequences_c_status_459095_idx'),
        ('analytics', '0006_alter_sendlog_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendlog',
            name='sequence_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='sequences.campaignstep'),
        ),
    ]
