# Generated by Django 4.2.13 on 2026-06-30 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0007_campaignstepvariant'),
        ('analytics', '0007_alter_sendlog_sequence_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='step_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='sequences.campaignstepvariant'),
        ),
    ]
