# Generated by Django 4.2.13 on 2026-07-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_sendlog_step_variant'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sendlog',
            name='analytics_s_contact_ca4978_idx',
        ),
        migrations.RemoveIndex(
            model_name='sendlog',
            name='analytics_s_smtp_ac_e3547a_idx',
        ),
        migrations.AddIndex(
            model_name='sendlog',
            index=models.Index(fields=['campaign', 'sent_at'], name='analytics_s_campaig_aaa252_idx'),
        ),
    ]
