# Generated by Django 4.2.13 on 2026-05-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
