# Generated by Django 4.2.13 on 2026-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_add_campaign_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
