# Generated by Django 4.2.13 on 2026-06-30 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='schedule_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_end_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
