# Generated by Django 4.2.13 on 2026-06-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_schedule_days_campaign_schedule_enabled_and_more'),
        # SendLog.campaign must be repointed away from campaigns.Campaign
        # before this migration drops the table it points to.
        ('analytics', '0006_alter_sendlog_campaign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignsmtproute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campaignsmtproute',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignsmtproute',
            name='smtp_account',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='CampaignSMTPRoute',
        ),
    ]
