# Generated by Django 4.2.13 on 2026-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0003_seed_system_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(blank=True, choices=[('cold_intro', 'Cold Intro'), ('follow_up', 'Follow-up'), ('breakup', 'Break-up'), ('meeting', 'Meeting'), ('case_study', 'Case Study'), ('referral', 'Referral'), ('event', 'Event'), ('pricing', 'Pricing/Demo'), ('reengagement', 'Re-engagement'), ('product_update', 'Product Update'), ('thank_you', 'Thank You'), ('news_jack', 'News-jack'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
