# Generated by Django 4.2.13 on 2026-06-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('unknown', 'Unknown')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
