# Generated by Django 4.2.13 on 2026-06-30 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_contact_verification_status_contact_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('manual', 'Manually added')], default='manual', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'email'], name='contacts_su_user_id_274db1_idx')],
                'unique_together': {('user', 'email')},
            },
        ),
    ]
