# Generated by Django 4.2.13 on 2026-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpaccount',
            name='_imap_password',
            field=models.TextField(blank=True, db_column='imap_password'),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='imap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='imap_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='imap_port',
            field=models.PositiveIntegerField(default=993),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='imap_use_ssl',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='imap_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='last_imap_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='last_imap_test_success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='last_imap_tested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='last_imap_uid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
