# Generated by Django 4.2.13 on 2026-06-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_accounts', '0002_smtpaccount__imap_password_smtpaccount_imap_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpaccount',
            name='signature_html',
            field=models.TextField(blank=True, help_text='Appended to outgoing replies/compose when enabled.'),
        ),
    ]
