# Generated by Django 4.2.13 on 2026-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_accounts', '0003_smtpaccount_signature_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpaccount',
            name='capture_cold_leads',
            field=models.BooleanField(default=False),
        ),
    ]
