# Generated by Django 4.2.13 on 2026-06-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_accounts', '0004_smtpaccount_capture_cold_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('target_daily', models.PositiveIntegerField(default=40, help_text='Warmup emails per day once fully ramped.')),
                ('ramp_step', models.PositiveIntegerField(default=4, help_text='Daily increase in warmup volume during ramp-up.')),
                ('reply_rate', models.PositiveIntegerField(default=35, help_text='Percent of received warmup emails to auto-reply to.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warmup', to='smtp_accounts.smtpaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WarmupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('is_reply', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_sent', to='smtp_accounts.smtpaccount')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warmup_received', to='smtp_accounts.smtpaccount')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['from_account', 'sent_at'], name='smtp_accoun_from_ac_4a8308_idx')],
            },
        ),
    ]
