# Generated by Django 4.2.13 on 2026-07-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_accounts', '0005_warmupsettings_warmupactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smtpaccount',
            name='weight',
        ),
    ]
