# Generated by Django 4.2.13 on 2026-09-21 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smtp_accounts', '0006_remove_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxOAuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('verifier', models.TextField()),
                ('nonce', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='_oauth_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='_oauth_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='oauth_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=16),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='oauth_reconnect_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='oauth_refresh_lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='oauth_subject',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddConstraint(
            model_name='smtpaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('oauth_provider', ''), _negated=True), fields=('user', 'oauth_provider', 'oauth_subject'), name='unique_oauth_mailbox_per_user'),
        ),
        migrations.AddField(
            model_name='mailboxoauthattempt',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smtp_accounts.smtpaccount'),
        ),
        migrations.AddField(
            model_name='mailboxoauthattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
