# Generated by Django 4.2.13 on 2026-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtp_accounts', '0007_mailboxoauthattempt_smtpaccount__oauth_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpaccount',
            name='bounce_disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='bounce_disabled_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smtpaccount',
            name='bounce_protection_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
