# Generated by Django 4.2.13 on 2026-07-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apollo_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
