# Generated by Django 4.2.13 on 2026-07-07 07:38
# Widens apollo_api_key to TextField (Fernet ciphertext is longer than the raw
# key) and renames the Python attribute to _apollo_api_key, keeping the same
# db_column so existing values are preserved rather than dropped/recreated.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_apollo_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apollo_api_key',
            field=models.TextField(blank=True, db_column='apollo_api_key'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apollo_api_key',
            new_name='_apollo_api_key',
        ),
    ]
