# Generated by Django 4.2.13 on 2026-06-27 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0004_sendlog_message_id_sendlog_replied_at_and_more'),
        ('smtp_accounts', '0002_smtpaccount__imap_password_smtpaccount_imap_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_unread', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_threads', to='contacts.contact')),
                ('smtp_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_threads', to='smtp_accounts.smtpaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'unique_together': {('user', 'contact', 'smtp_account')},
            },
        ),
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('in_reply_to', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_messages', to='analytics.sendlog')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.thread')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
