# Generated by Django 4.2.13 on 2026-06-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'is_unread'], name='inbox_threa_user_id_f107dd_idx'),
        ),
    ]
