# Generated by Django 4.2.13 on 2026-06-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_thread_inbox_threa_user_id_f107dd_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='lead_status',
            field=models.CharField(choices=[('none', 'None'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('meeting_booked', 'Meeting Booked')], default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'lead_status'], name='inbox_threa_user_id_90db9d_idx'),
        ),
    ]
