# Generated by Django 4.2.13 on 2026-06-29 08:19

import apps.inbox.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_attachment_replytemplate_thread_lead_status_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location='D:\\p_project\\email_marketing\\backend\\private_media'), upload_to=apps.inbox.models.attachment_upload_path),
        ),
    ]
