# Generated by Django 4.2.13 on 2026-06-29 08:35

from django.db import migrations, models


def backfill_last_message_direction(apps, schema_editor):
    Thread = apps.get_model('inbox', 'Thread')
    for thread in Thread.objects.all():
        last = thread.messages.order_by('-occurred_at').first()
        if last:
            thread.last_message_direction = last.direction
            thread.save(update_fields=['last_message_direction'])


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_message_direction',
            field=models.CharField(blank=True, choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'last_message_direction', 'last_message_at'], name='inbox_threa_user_id_084272_idx'),
        ),
        migrations.RunPython(backfill_last_message_direction, migrations.RunPython.noop),
    ]
