# Generated by Django 4.2.13 on 2026-06-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_thread_last_message_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_cold_lead',
            field=models.BooleanField(default=False),
        ),
    ]
