"""Refresh the vendored disposable-domains blocklist from public sources.

Temp-mail platforms (Boomlify, etc.) spin up new throwaway domains constantly, so a
static file goes stale. This command re-downloads the big community-maintained lists,
merges them with our local seed, and rewrites data/disposable_domains.txt.

    python manage.py refresh_disposable_domains

Run it on a schedule (a weekly Celery beat entry calls this) to stay current. It only
fetches public plain-text lists — no third-party API/keys involved. If every source is
unreachable it leaves the existing file untouched and exits non-zero.
"""
import re
from pathlib import Path
from urllib.request import urlopen, Request

from django.core.management.base import BaseCommand

# Public, plain-text disposable-domain blocklists (one domain per line, '#' = comment).
SOURCES = [
    'https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.txt',
    'https://raw.githubusercontent.com/7c/fakefilter/main/txt/data.txt',
    'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/main/disposable_email_blocklist.conf',
]

_DATA_FILE = Path(__file__).resolve().parents[2] / 'data' / 'disposable_domains.txt'
_SEED_FILE = Path(__file__).resolve().parents[2] / 'data' / 'disposable_seed.txt'
_DOMAIN_RE = re.compile(r'^[a-z0-9.-]+\.[a-z]{2,}$')

_HEADER = (
    '# Disposable / temporary email domains — one per line, lowercased.\n'
    '# Auto-generated by `manage.py refresh_disposable_domains` from public blocklists\n'
    '# plus data/disposable_seed.txt. Lines starting with # are ignored by the loader.\n'
)


class Command(BaseCommand):
    help = 'Refresh the disposable-email-domain blocklist from public sources.'

    def add_arguments(self, parser):
        parser.add_argument('--timeout', type=int, default=30, help='Per-source fetch timeout (s).')

    def handle(self, *args, **opts):
        domains = set()

        # Local seed (hand-maintained additions that must always be present).
        if _SEED_FILE.exists():
            domains |= self._parse(_SEED_FILE.read_text(encoding='utf-8'))

        fetched_any = False
        for url in SOURCES:
            try:
                req = Request(url, headers={'User-Agent': 'mailflow-disposable-refresh'})
                with urlopen(req, timeout=opts['timeout']) as resp:
                    text = resp.read().decode('utf-8', 'ignore')
                added = self._parse(text)
                domains |= added
                fetched_any = True
                self.stdout.write(f'  {url} -> {len(added):,} domains')
            except Exception as e:
                self.stderr.write(self.style.WARNING(f'  skip {url}: {e}'))

        if not fetched_any:
            self.stderr.write(self.style.ERROR('No sources reachable; keeping existing list.'))
            raise SystemExit(1)

        ordered = sorted(domains)
        _DATA_FILE.write_text(_HEADER + '\n'.join(ordered) + '\n', encoding='utf-8')
        self.stdout.write(self.style.SUCCESS(f'Wrote {len(ordered):,} disposable domains to {_DATA_FILE.name}'))

    @staticmethod
    def _parse(text):
        out = set()
        for line in text.splitlines():
            line = line.strip().lower()
            if not line or line.startswith('#'):
                continue
            if _DOMAIN_RE.match(line):
                out.add(line)
        return out
