# Generated by Django 4.2.13 on 2026-06-27 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smtp_accounts', '0001_initial'),
        ('contacts', '0001_initial'),
        ('email_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('use_custom_smtp_routing', models.BooleanField(default=False)),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_lists', models.ManyToManyField(related_name='sequences', to='contacts.contactlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=500)),
                ('html_content', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('campaign_variables', models.JSONField(blank=True, default=dict)),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('stop_on_open', models.BooleanField(default=False)),
                ('stop_on_click', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sequences.sequence')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequence_steps', to='email_templates.emailtemplate')),
            ],
            options={
                'ordering': ['sequence', 'order'],
                'unique_together': {('sequence', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SequenceSMTPRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smtp_routes', to='sequences.sequence')),
                ('smtp_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_routes', to='smtp_accounts.smtpaccount')),
            ],
            options={
                'unique_together': {('sequence', 'smtp_account')},
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], default='active', max_length=20)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='contacts.contact')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sequences.sequencestep')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='sequences.sequence')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['status', 'next_send_at'], name='sequences_s_status_5df17f_idx')],
                'unique_together': {('sequence', 'contact')},
            },
        ),
    ]
