# Generated by Django 4.2.13 on 2026-06-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sequencestep',
            unique_together=set(),
        ),
    ]
