# Generated by Django 4.2.13 on 2026-06-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_alter_sequencestep_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='stop_on_reply',
            field=models.BooleanField(default=True),
        ),
    ]
