# Generated by Django 4.2.13 on 2026-06-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0005_rename_sequence_to_campaign'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignenrollment',
            new_name='sequences_c_status_459095_idx',
            old_name='sequences_s_status_5df17f_idx',
        ),
    ]
