# Generated by Django 4.2.13 on 2026-06-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0007_campaignstepvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstep',
            name='auto_optimize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='auto_optimize_metric',
            field=models.CharField(choices=[('open_rate', 'Open Rate'), ('click_rate', 'Click Rate'), ('reply_rate', 'Reply Rate')], default='reply_rate', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignstep',
            name='auto_optimize_min_sends',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
