# Generated by Django 4.2.13 on 2026-07-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0008_campaignstep_auto_optimize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignstepvariant',
            name='weight',
        ),
    ]
