# Generated by Django 4.2.13 on 2026-07-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0009_remove_variant_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='use_custom_smtp_routing',
        ),
        migrations.DeleteModel(
            name='CampaignSMTPRoute',
        ),
    ]
