# Generated by Django 4.2.13 on 2026-07-02 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0011_campaign_smtp_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('opened', 'Opened'), ('not_opened', 'Not Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('default', 'Default (always)')], max_length=20)),
                ('wait_days', models.PositiveIntegerField(default=1)),
                ('wait_hours', models.PositiveIntegerField(default=0)),
                ('next_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sequences.campaignstep')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='sequences.campaignstep')),
            ],
            options={
                'ordering': ['condition'],
                'unique_together': {('step', 'condition')},
            },
        ),
    ]
