# Generated by Django 4.2.13 on 2026-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0012_add_step_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstepvariant',
            name='weight',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
