# Generated by Django 4.2.13 on 2026-07-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0013_campaignstepvariant_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='daily_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='text_only',
            field=models.BooleanField(default=False),
        ),
    ]
