# Generated by Django 4.2.13 on 2026-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0014_campaign_daily_limit_campaign_text_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='auto_pause_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auto_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='auto_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounce_auto_disable_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounce_minimum_sends',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounce_pause_threshold',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounce_protection_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='bounce_window_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
    ]
